version: '3.8'

services:
  frontend:
    image: frontend-todo
    stdin_open: true
    ports:
      - 3000:3000
    networks:
        - mern-todo-app
    command: [ "/usr/local/bin/yarn", "run", "serve", "--port", "3000" ]

  backend:
    image: backend
    ports:
      - 8080:8080
    networks:
        - mern-todo-app
    depends_on:
      - mongo
    command: [ "node" , "./build/index.js"]

  mongo:
      image: mongo
      ports:
        - 27018:27017
      networks:
        - mern-todo-app
      volumes:
        - mongodb:/data/db
        - mongodb_config:/data/configdb
volumes:
  mongodb:
    driver: local
  mongodb_config:
    driver: local

networks:
  mern-todo-app:
    driver: bridge