runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  MONGO_DB_URL: ""
  MONGO_DB_TEST_URL: ""
  PORT: 8080
  APP_NAME: "Todo App"
  FRONT_END_URL: ""
