runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  MONGO_DB_URL: "mongodb+srv://success:21Computer@cluster0.urj3nyz.mongodb.net/todo?retryWrites=true&w=majority"
  MONGO_DB_TEST_URL: "mongodb+srv://success:21Computer@cluster0.urj3nyz.mongodb.net/todo_test?retryWrites=true&w=majority"
  PORT: 8080
  APP_NAME: "Todo App"
  FRONT_END_URL: "https://dmoxyeze.github.io"
