runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  MONGO_DB_URL: "mongodb+srv://success:DQn58sMQwoSCkqmJ@cluster0.x8sudj2.mongodb.net/?retryWrites=true&w=majority/todo"
  MONGO_DB_TEST_URL: "mongodb+srv://success:DQn58sMQwoSCkqmJ@cluster0.x8sudj2.mongodb.net/?retryWrites=true&w=majority/todo_test"
  PORT: 8080
  APP_NAME: "Todo App"
  FRONT_END_URL: "https://dmoxyeze.github.io"
